import { useCallback, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import rehypeRaw from 'rehype-raw';
import SyntaxHighlighter from 'react-syntax-highlighter';
import { atomOneDark } from 'react-syntax-highlighter/dist/esm/styles/hljs';
import blackboardTheme from 'monaco-themes/themes/Blackboard.json';
import Editor from '@monaco-editor/react';


function App() {
    // States to hold the code from the textarea, documentation generated by the API and loading status
    const [code, setCode] = useState('');
    const [documentation, setDocumentation] = useState('');
    const [isLogicIntact, setIsLogicIntact] = useState(null);
    const [verificationMessage, setVerificationMessage] = useState('');
    const [pipelineStep, setPipelineStep] = useState(0); // 0=idle, 1=architect, 2=documenter, 3=verifier, 4=complete
    const [errorMessage, setErrorMessage] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [copied, setCopied] = useState(false);

    const handleCopy = () => {
        navigator.clipboard.writeText(documentation);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    function handleEditorChange(value, event) {
        setCode(value);
    }

    function handleEditorWillMount(monaco) {
        // --- CHANGED: Register our theme under the name "blackboard" ---
        monaco.editor.defineTheme('blackboard', blackboardTheme);
    }
    // Make the function async to use await
    const handleSubmit = async () => {
        // Set loading state and clear previous documentation
        setIsLoading(true);
        setPipelineStep(0);
        setErrorMessage('');
        setDocumentation('');
        setIsLogicIntact(null);
        setVerificationMessage('');

        try {
            const response = await fetch(`${import.meta.env.VITE_API_BASE_URL}/api/document`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ code }),
            });

            // Check if the request was not successful
            if (!response.ok) {
                const errorData = await response.json();
                throw new Error(errorData.error || 'Something went wrong');
            }

            // SSE Chunk Reader Logic
            const reader = response.body.getReader();
            const decoder = new TextDecoder();
            let done = false;
            let buffer = '';

            while (!done) {
                const { value, done: readerDone } = await reader.read();
                done = readerDone;

                if (value) {
                    const chunk = decoder.decode(value, { stream: true });
                    buffer += chunk;

                    // Server sends events divided by \n\n
                    const parts = buffer.split('\n\n');

                    // The very last part might be an incomplete chunk, keep it in the buffer
                    buffer = parts.pop() || '';

                    for (const part of parts) {
                        const trimmedPart = part.trim();
                        if (!trimmedPart) continue;

                        let dataStr = '';
                        if (trimmedPart.startsWith('data:')) {
                            // Strip 'data:' prefix and trailing/leading spaces
                            dataStr = trimmedPart.substring(5).trim();
                        } else {
                            continue;
                        }

                        try {
                            const parsed = JSON.parse(dataStr);

                            if (parsed.step === 'error') {
                                setErrorMessage(parsed.message);
                                setIsLoading(false);
                                done = true;
                                break;
                            } else if (parsed.step === 'complete') {
                                setPipelineStep(4);
                                // The backend explicitly sends: res.write(`data: ${JSON.stringify({ step: 'complete', data: { documentation: ... } })}\n\n`);
                                // So we MUST access parsed.data to get the payload
                                if (parsed.data && parsed.data.documentation) {
                                    setDocumentation(parsed.data.documentation);
                                    setIsLogicIntact(parsed.data.isLogicIntact);
                                    setVerificationMessage(parsed.data.verificationMessage);
                                } else {
                                    throw new Error("Received 'complete' step but payload data is missing or malformed.");
                                }
                            } else {
                                // Update the numeric pipeline step for the UI stepper
                                if (parsed.step === 1) setPipelineStep(1);
                                else if (parsed.step === 2) setPipelineStep(2);
                                else if (parsed.step === 3) setPipelineStep(3);
                            }
                        } catch (e) {
                            console.error("Error parsing JSON chunk:", dataStr);
                        }
                    }
                }
            }

        } catch (error) {
            console.error('Failed to fetch documentation:', error);
            setErrorMessage(`Error: ${error.message}`);
        } finally {
            // Fail-safe: If the loop finishes but documentation is still empty, show an error.
            setIsLoading(false);
            setDocumentation((prevDoc) => {
                if (!prevDoc && pipelineStep !== 4) {
                    setErrorMessage("Error: Stream disconnected before documentation could be generated.");
                }
                return prevDoc;
            });
        }
    };

    const handleKeyDown = (e) => {
        if (e.key === 'Tab') {
            e.preventDefault();

            // Use the browser's built-in 'insertText' command
            // This is treated as a native user action and is undoable.
            document.execCommand('insertText', false, '    '); // Inserts 4 spaces
        }
    };

    // Markdown interception: dynamically extract the Title and wrap Source Code in <details>
    let displayTitle = 'Technical Documentation';
    let renderableDocs = documentation;
    if (renderableDocs) {
        // Extract top-level generic headers (e.g., "# Technical Documentation...")
        const titleMatch = renderableDocs.match(/^#+\s*(.+)(\n|$)/);
        if (titleMatch) {
            displayTitle = titleMatch[1].trim();
            // Strip it so we don't duplicate the title in the body
            renderableDocs = renderableDocs.replace(/^#+\s*(.+)(\n|$)/, '');
        }

        // Dynamically wrap the "## Source Code" and its code block in an HTML accordion
        renderableDocs = renderableDocs.replace(
            /##\s*Source\s*Code[\s\S]*?(```[\s\S]+?```)/i,
            '<details>\n<summary>View Source Code</summary>\n\n$1\n\n</details>'
        );
    }

    return (
        <div className="app-container">
            <h1>AI Code Documentation Generator</h1>
            <p>Paste your function in any language below and get instant documentation.</p>

            <div className="editor-container">
                <Editor
                    height="40vh"
                    defaultLanguage="typescript"
                    value={code}
                    onChange={handleEditorChange}
                    beforeMount={handleEditorWillMount}
                    theme="blackboard"
                    options={{
                        minimap: { enabled: false },
                        scrollBeyondLastLine: false,
                        wordWrap: 'on'
                    }}
                />
                {/* This placeholder div will only render when 'code' is empty */}
                {!code && (
                    <div className="editor-placeholder">
                        e.g., function greet(name: string) {'{'}{'  '}return `Hello, ${'${name}'}!`;{'}'}
                    </div>
                )}
            </div>

            <button onClick={handleSubmit} disabled={isLoading || !code}>
                {isLoading ? 'Processing Pipeline...' : 'Generate Documentation'}
            </button>

            {errorMessage && (
                <div className="error-alert">
                    {errorMessage}
                </div>
            )}

            {isLoading && !errorMessage && (
                <div className="pipeline-stepper">
                    <div className={`step-node ${pipelineStep >= 1 ? (pipelineStep > 1 ? 'completed' : 'active') : ''}`}>
                        <div className="step-circle"></div>
                        <div className="step-label">AST Extraction</div>
                    </div>
                    <div className={`step-node ${pipelineStep >= 2 ? (pipelineStep > 2 ? 'completed' : 'active') : ''}`}>
                        <div className="step-circle"></div>
                        <div className="step-label">LLM Generation</div>
                    </div>
                    <div className={`step-node ${pipelineStep >= 3 ? (pipelineStep > 3 ? 'completed' : 'active') : ''}`}>
                        <div className="step-circle"></div>
                        <div className="step-label">Logic Verification</div>
                    </div>
                </div>
            )}

            {documentation && !isLoading && (
                <div className="documentation-display">
                    <div className="doc-header-action-bar">
                        <h2 className="doc-title">{displayTitle}</h2>
                        <button className="copy-btn" onClick={handleCopy}>
                            {copied ? 'Copied!' : 'Copy as Markdown'}
                        </button>
                    </div>

                    <ReactMarkdown
                        remarkPlugins={[remarkGfm]}
                        rehypePlugins={[rehypeRaw]}
                        components={{
                            code(props) {
                                const {children, className, node, ...rest} = props;
                                const match = /language-(\w+)/.exec(className || '');
                                return match ? (
                                    <SyntaxHighlighter
                                        {...rest}
                                        PreTag="div"
                                        children={String(children).replace(/\n$/, '')}
                                        language={match[1]}
                                        style={atomOneDark}
                                        showLineNumbers
                                        wrapLongLines={true}
                                    />
                                ) : (
                                    <code {...rest} className={className}>
                                        {children}
                                    </code>
                                );
                            }
                        }}
                    >
                        {renderableDocs}
                    </ReactMarkdown>
                    {isLogicIntact !== null && (
                        <div className={`verification-badge ${isLogicIntact ? 'success' : 'warning'}`} style={{
                            padding: '12px',
                            marginTop: '30px',
                            borderRadius: '6px',
                            backgroundColor: isLogicIntact ? '#1e4620' : '#4a1515',
                            color: isLogicIntact ? '#a3e4b5' : '#fcb6b6',
                            border: `1px solid ${isLogicIntact ? '#2a632d' : '#802626'}`,
                            fontFamily: 'system-ui, -apple-system, sans-serif'
                        }}>
                            <strong>{isLogicIntact ? '[VERIFIED LOGIC]' : '[WARNING]'}</strong> {verificationMessage}
                        </div>
                    )}
                </div>
            )}
        </div>
    );
}

export default App;